language: java
sudo: true
dist: trusty
deploy:
  script: "mvn install"
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: *
script: 
- echo "skipping tests"
before_install:
  - chmod +x mvnw
